/**/helm_manager:
  ros__parameters:
    output_type: 'twist'
    max_yaw_speed: 0.74   
    max_speed: 3.3

/**/mbes_bridge:
  ros__parameters:
    bridge_names:
      - multibeam_sonar_pointcloud
    bridges:
      multibeam_sonar_pointcloud:
        gz_topic_name: /wamv/multibeam_sonar/sonar_data/point_cloud
        ros_topic_name: "sensors/multibeam_sonar/points"
        gz_type_name: gz.msgs.PointCloudPacked
        ros_type_name: sensor_msgs/msg/PointCloud2
        direction: "GZ_TO_ROS"
        lazy: false



/**/mru_transform:
  ros__parameters:
    sensors:
      gazebo:
        topics:
          orientation: "sensors/imu/imu/data"
          position: "sensors/gps/gps/fix"
          velocity: "sensors/gps/gps/velocity"
    sensor_names:
    - gazebo

/**/platform_sender:
  ros__parameters:
    width: 2.44
    length: 4.85
    color:
      red: 0.4
      green: 0.7
      blue: 0.4

    nav:
      source_names:
        - gazebo
      sources:
        gazebo:
          topics:
            orientation: "sensors/imu/imu/data"
            position: "sensors/gps/gps/fix"
            velocity: "sensors/gps/gps/velocity"
