/ben/udp_bridge:
  ros__parameters:
    name: ben
    port: 4200
    maximum_packet_size: 1000
    remotes_list:
      - operator
    remotes:
      operator:
        connections_list:
          - default
        connections:
          default:
            host: localhost
            port: 4201
            maximum_bytes_per_second: 50000
            topics_list:
            - odom
            - marine_autonomy-heartbeat
            - marine_autonomy-nav-orientation
            - marine_autonomy-nav-position
            - marine_autonomy-nav-velocity
            - marine_autonomy-platforms
            - marine_autonomy-response
            - marine_autonomy-status-mission-manager
            topics:
              odom: {source: odom}
              marine_autonomy-heartbeat: {source: marine/heartbeat}
              marine_autonomy-nav-orientation: {source: marine/nav/orientation}
              marine_autonomy-nav-position: {source: marine/nav/position}
              marine_autonomy-nav-velocity: {source: marine/nav/velocity}
              marine_autonomy-platforms: {source: /marine/platforms}
              marine_autonomy-response: {source: marine/response}
              marine_autonomy-status-mission-manager: {source: marine/status/mission_manager}

/operator/udp_bridge:
  ros__parameters:
    name: operator
    port: 4201
    maximum_packet_size: 1000
    remotes_list:
      - ben
    remotes:
      ben:
        connections_list:
          - default
        connections:
          default:
            host: localhost
            port: 4200
            maximum_bytes_per_second: 50000
            topics_list:
            - piloting_mode-manual-helm
            topics:
              piloting_mode-manual-helm: {source: 'piloting_mode/manual/helm'}
