<?xml version="1.0"?>
<package format="2">
  <name>project11_simulation</name>
  <version>0.0.0</version>
  <description>
    Project11 packages related robot simulation
  </description>

  <author email="roland@ccom.unh.edu">Roland Arsenault</author>
  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>
  <exec_depend>asv_helm</exec_depend>
  <exec_depend>asv_sim</exec_depend>
  <exec_depend>cube_bathymetry</exec_depend>
  <exec_depend>grid_map_rviz_plugin</exec_depend>
  <exec_depend>project11</exec_depend>
  <exec_depend>mbes_sim</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <test_depend>ament_lint_auto</test_depend>

  <!-- this recursively depends on a set of common linters -->
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
